name: Check

on:
  pull_request:
    paths:
      - .github/workflows/check.yml
      - crates/**
      - Cargo.*
      - "!**/*.md"
  push:
    branches:
      - main
    paths:
      - .github/workflows/check.yml
      - crates/**
      - Cargo.*
      - "!**/*.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Run cargo fmt
        run: |
          rustup component add rustfmt
          cargo fmt \
            --all \
            --check

  cargo-clippy:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Cache Rust
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - name: Run cargo clippy
        shell: bash
        run: |
          rustup component add clippy
          cargo clippy \
            --all-targets \
            --all-features \
            --locked \
            -- \
            -D warnings

  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        r-version:
          - release
        include:
          - os: ubuntu-latest
            r-version: devel
          - os: windows-latest
            r-version: devel
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Air CLI
        uses: posit-dev/setup-air@cf390573ff4fe0f198f35df3a642b1409328d859 # v1
      - name: Install R
        uses: r-lib/actions/setup-r@a51a8012b0aab7c32ef9d19bf54da93f3254335e # v2
        with:
          r-version: ${{ matrix.r-version }}
          use-public-rspm: true
          Ncpus: "2"
      - name: Install R packages for tests
        uses: r-lib/actions/setup-r-dependencies@a51a8012b0aab7c32ef9d19bf54da93f3254335e # v2
        with:
          working-directory: crates/arf-console/tests/r-deps
          dependencies: '"hard"'
      - name: Cache Rust
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - name: Run tests
        run: >
          cargo test
          --all-targets
          --all-features
          --workspace
          --locked
